In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
USER = 'root'
PASSWORD = 'Abhi8383055393'
HOST = 'localhost'
PORT = '3306'
DATABASE = 'ecommmerce_analysis'

In [4]:
engine = create_engine("sqlite:///C:/Users/abhis/OneDrive/Documents/abhishek/Data_Analyst_Abhishek/data_analyst/python_data/practice/enterprise ecommerce project/database/managing.db")

In [5]:
connection_string = f"mysql+pymysql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"

In [6]:
# mysql engine 
mysql_engine = create_engine(connection_string)

In [7]:
# read csv customer file
customers = pd.read_csv("C:/Users/abhis/OneDrive/Documents/abhishek/Data_Analyst_Abhishek/data_analyst/python_data/practice/enterprise ecommerce project/data/customers.csv")
customers.head()

,customer_id,customer_name,gender,age,city,state,country,join_date,customer_segment
0,CUST07363,Bakhshi Shenoy,Male,70.0,Mumbai,Punjab,India,2021-10-20,Small Business
1,CUST02185,Avni Thaman,Female,63.0,Surat,Gujarat,India,2022-04-30,Small Business
2,CUST06157,Oliver Kade,Female,66.0,Pune,Maharashtra,India,2021-09-11,Home Office
3,CUST06163,Udarsh Ganesh,Male,38.0,Amritsar,Punjab,India,2021-02-05,Consumer
4,CUST04599,Girindra Bail,Male,68.0,Ahmedabad,Gujarat,India,2024-06-12,Home Office

In [8]:
# load to sql
customers.to_sql("customers", engine, if_exists='replace', index=False)

10040

In [9]:
pd.read_sql_query('Select * from customers', engine)

,customer_id,customer_name,gender,age,city,state,country,join_date,customer_segment
0,CUST07363,Bakhshi Shenoy,Male,70.0,Mumbai,Punjab,India,2021-10-20,Small Business
1,CUST02185,Avni Thaman,Female,63.0,Surat,Gujarat,India,2022-04-30,Small Business
2,CUST06157,Oliver Kade,Female,66.0,Pune,Maharashtra,India,2021-09-11,Home Office
3,CUST06163,Udarsh Ganesh,Male,38.0,Amritsar,Punjab,India,2021-02-05,Consumer
4,CUST04599,Girindra Bail,Male,68.0,Ahmedabad,Gujarat,India,2024-06-12,Home Office
...,...,...,...,...,...,...,...,...,...
10035,CUST05735,Gaurangi Sood,None,69.0,Surat,Gujarat,India,2023-04-29,Corporate
10036,CUST05192,Banjeet Ben,Female,23.0,Jaipur,Rajasthan,India,2024-02-15,Small Business
10037,CUST05391,Ikbal Bhargava,Female,23.0,Ludhiana,Punjab,India,2023-10-25,Consumer
10038,CUST00861,Owen Dey,Female,45.0,Jaipur,Rajasthan,India,2026-03-17,Home Office
10039,CUST07271,Pratyush Virk,Male,56.0,Bangalore,Karnataka,India,2025-01-23,Home Office

In [10]:
# # python practice
# isnull()
# fillna()
# drop_duplicates()
# .duplicated()
# type conversion
# outlier detection
# invalid value detection
# string cleaning

# gender and age have null value

In [11]:
customers = customers.drop_duplicates(subset='customer_id').reset_index(drop=True)

In [12]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       10000 non-null  object
 1   customer_name     10000 non-null  object
 2   gender            9800 non-null   object
 3   age               9750 non-null   float64
 4   city              10000 non-null  object
 5   state             10000 non-null  object
 6   country           10000 non-null  object
 7   join_date         10000 non-null  object
 8   customer_segment  10000 non-null  object
dtypes: float64(1), object(8)
memory usage: 703.3+ KB

In [13]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       10000 non-null  object
 1   customer_name     10000 non-null  object
 2   gender            9800 non-null   object
 3   age               9750 non-null   float64
 4   city              10000 non-null  object
 5   state             10000 non-null  object
 6   country           10000 non-null  object
 7   join_date         10000 non-null  object
 8   customer_segment  10000 non-null  object
dtypes: float64(1), object(8)
memory usage: 703.3+ KB

In [14]:
# for formating the date column and create new columns for it
customers['join_date'] = pd.to_datetime(customers['join_date'], format='mixed', errors='coerce')
customers['join_month'] = customers['join_date'].dt.to_period('M').astype(str)
customers['join_year'] = customers['join_date'].dt.year

In [15]:
customers['join_date'].value_counts()

join_date
2032-01-01    20
2026-04-29    14
2021-08-02    12
2024-05-05    12
2021-10-05    12
              ..
2023-10-05     1
2021-08-18     1
2025-09-27     1
2026-05-20     1
2025-02-10     1
Name: count, Length: 2176, dtype: int64

In [16]:
customers['join_date'].value_counts()

join_date
2032-01-01    20
2026-04-29    14
2021-08-02    12
2024-05-05    12
2021-10-05    12
              ..
2023-10-05     1
2021-08-18     1
2025-09-27     1
2026-05-20     1
2025-02-10     1
Name: count, Length: 2176, dtype: int64

In [17]:
# remove na in gender
customers = customers[customers['gender'].isna() == False]

In [18]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9800 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       9800 non-null   object
 1   customer_name     9800 non-null   object
 2   gender            9800 non-null   object
 3   age               9556 non-null   float64
 4   city              9800 non-null   object
 5   state             9800 non-null   object
 6   country           9800 non-null   object
 7   join_date         9800 non-null   datetime64[ns]
 8   customer_segment  9800 non-null   object
 9   join_month        9800 non-null   object
 10  join_year         9800 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(1), object(8)
memory usage: 880.5+ KB

In [19]:
customers['age'] = customers['age'].fillna(customers.groupby(['gender', 'state'])['age'].transform('median'))
# customers.groupby(['gender', 'state'])['age'].transform('median')

In [20]:
# age outliers
min_age = customers['age'].quantile(0.25)
max_age = customers['age'].quantile(0.75)

iqr = max_age - min_age

lower_age = min_age - 1.5 * iqr
upper_age = max_age + 1.5 * iqr

outlier = customers[
    (
        customers['age'] < lower_age
    ) | (
        customers['age'] > upper_age
    )
]

customers = customers[
    (
        customers['age'] >= lower_age
    ) & (
        customers['age'] <= upper_age
    )
]

print(f"Number of outliers: {len(outlier)}")
print(f"Percentage: {len(outlier) / len(customers) * 100:.2f}%")

Number of outliers: 15
Percentage: 0.15%

In [21]:
customers['age'].min()

np.float64(18.0)

In [22]:
# add the customers data load into sql database
customers.to_sql("customers", engine, if_exists='replace' , index=False )

9785

In [23]:
pd.read_sql_query('select * from customers limit 5', engine)

,customer_id,customer_name,gender,age,city,state,country,join_date,customer_segment,join_month,join_year
0,CUST07363,Bakhshi Shenoy,Male,70.0,Mumbai,Punjab,India,2021-10-20 00:00:00.000000,Small Business,2021-10,2021
1,CUST02185,Avni Thaman,Female,63.0,Surat,Gujarat,India,2022-04-30 00:00:00.000000,Small Business,2022-04,2022
2,CUST06157,Oliver Kade,Female,66.0,Pune,Maharashtra,India,2021-09-11 00:00:00.000000,Home Office,2021-09,2021
3,CUST06163,Udarsh Ganesh,Male,38.0,Amritsar,Punjab,India,2021-02-05 00:00:00.000000,Consumer,2021-02,2021
4,CUST04599,Girindra Bail,Male,68.0,Ahmedabad,Gujarat,India,2024-06-12 00:00:00.000000,Home Office,2024-06,2024

In [24]:
# # sql questions 
# Find duplicate customers.
# Find customers with invalid ages.
# Find future join dates.
# Find missing genders.
# Count customers by segment.
# Top states by customer count.
# Monthly customer acquisition.

In [25]:
# Find duplicate customers.
pd.read_sql_query("""
with dupp_value as (
    select customer_id, row_number() over(partition by customer_id order by join_date) as rnk
    from customers)
    select customer_id
    from dupp_value
    where rnk > 1
""" , engine)

Empty DataFrame
Columns: [customer_id]
Index: []

In [26]:
# Find customers with invalid ages.
pd.read_sql_query('''
    select 
        * from customers
    where age is not null and age > 0 and age < 120
''', engine)

,customer_id,customer_name,gender,age,city,state,country,join_date,customer_segment,join_month,join_year
0,CUST07363,Bakhshi Shenoy,Male,70.0,Mumbai,Punjab,India,2021-10-20 00:00:00.000000,Small Business,2021-10,2021
1,CUST02185,Avni Thaman,Female,63.0,Surat,Gujarat,India,2022-04-30 00:00:00.000000,Small Business,2022-04,2022
2,CUST06157,Oliver Kade,Female,66.0,Pune,Maharashtra,India,2021-09-11 00:00:00.000000,Home Office,2021-09,2021
3,CUST06163,Udarsh Ganesh,Male,38.0,Amritsar,Punjab,India,2021-02-05 00:00:00.000000,Consumer,2021-02,2021
4,CUST04599,Girindra Bail,Male,68.0,Ahmedabad,Gujarat,India,2024-06-12 00:00:00.000000,Home Office,2024-06,2024
...,...,...,...,...,...,...,...,...,...,...,...
9780,CUST06266,Anvi Mand,Male,28.0,Kanpur,Uttar Pradesh,India,2025-09-02 00:00:00.000000,Consumer,2025-09,2025
9781,CUST05192,Banjeet Ben,Female,23.0,Jaipur,Rajasthan,India,2024-02-15 00:00:00.000000,Small Business,2024-02,2024
9782,CUST05391,Ikbal Bhargava,Female,23.0,Ludhiana,Punjab,India,2023-10-25 00:00:00.000000,Consumer,2023-10,2023
9783,CUST00861,Owen Dey,Female,45.0,Jaipur,Rajasthan,India,2026-03-17 00:00:00.000000,Home Office,2026-03,2026
9784,CUST07271,Pratyush Virk,Male,56.0,Bangalore,Karnataka,India,2025-01-23 00:00:00.000000,Home Office,2025-01,2025

In [27]:
# Find future join dates.
pd.read_sql_query('''
select * from customers where join_date > current_date ''', engine)

,customer_id,customer_name,gender,age,city,state,country,join_date,customer_segment,join_month,join_year
0,CUST06974,Madhavi Ganesh,Male,27.0,Jaipur,Rajasthan,India,2032-01-01 00:00:00.000000,Home Office,2032-01,2032
1,CUST06348,Chatresh Khatri,Male,58.0,Amritsar,Punjab,India,2032-01-01 00:00:00.000000,Small Business,2032-01,2032
2,CUST02817,Darsh Bath,Female,19.0,Gurgaon,Haryana,India,2032-01-01 00:00:00.000000,Consumer,2032-01,2032
3,CUST01484,Eiravati Konda,Male,19.0,Ahmedabad,Gujarat,India,2032-01-01 00:00:00.000000,Corporate,2032-01,2032
4,CUST01469,Chaitanya Borra,Female,37.0,Coimbatore,Tamil Nadu,India,2032-01-01 00:00:00.000000,Home Office,2032-01,2032
5,CUST00787,Mitesh Chandran,Male,54.0,New Delhi,Delhi,India,2032-01-01 00:00:00.000000,Small Business,2032-01,2032
6,CUST08282,Tripti Golla,Female,22.0,Amritsar,Punjab,India,2032-01-01 00:00:00.000000,Corporate,2032-01,2032
7,CUST09971,Aarna Pal,Male,69.0,Chennai,Tamil Nadu,India,2032-01-01 00:00:00.000000,Home Office,2032-01,2032
8,CUST00758,Jagdish Som,Female,21.0,Ludhiana,Punjab,India,2032-01-01 00:00:00.000000,Consumer,2032-01,2032
9,CUST07336,Vasudha Malhotra,Female,26.0,Chennai,Tamil Nadu,India,2032-01-01 00:00:00.000000,Corporate,2032-01,2032
10,CUST04934,Kritika Basu,Male,57.0,Amritsar,Punjab,India,2032-01-01 00:00:00.000000,Corporate,2032-01,2032
11,CUST06110,Jagat Kamdar,Male,54.0,New Delhi,Delhi,India,2032-01-01 00:00:00.000000,Home Office,2032-01,2032
12,CUST08047,Reva Palla,Male,38.0,Noida,Uttar Pradesh,India,2032-01-01 00:00:00.000000,Small Business,2032-01,2032
13,CUST07518,Vrinda Chakraborty,Male,20.0,Pune,Maharashtra,India,2032-01-01 00:00:00.000000,Consumer,2032-01,2032
14,CUST01629,Alka Koshy,Male,52.0,Mumbai,Maharashtra,India,2032-01-01 00:00:00.000000,Corporate,2032-01,2032
15,CUST06525,Naksh Mittal,Female,34.0,Bangalore,Karnataka,India,2032-01-01 00:00:00.000000,Corporate,2032-01,2032
16,CUST09001,Saanvi Joshi,Female,22.0,Kolkata,West Bengal,India,2032-01-01 00:00:00.000000,Home Office,2032-01,2032
17,CUST06137,Jasmit Warrior,Male,35.0,Surat,Gujarat,India,2032-01-01 00:00:00.000000,Home Office,2032-01,2032
18,CUST08151,Bhanumati Nair,Male,61.0,Mumbai,Maharashtra,India,2032-01-01 00:00:00.000000,Small Business,2032-01,2032

In [28]:
# Find missing genders.
pd.read_sql_query("""
select customer_id, customer_name, gender  from customers where gender is null """, engine)

Empty DataFrame
Columns: [customer_id, customer_name, gender]
Index: []

In [29]:
# Count customers by segment.
pd.read_sql_query('''
select customer_segment , count(customer_id) as total_customer_count from customers group by customer_segment order by total_customer_count desc''', engine)

  customer_segment  total_customer_count
0        Corporate                  2509
1   Small Business                  2456
2         Consumer                  2448
3      Home Office                  2372

In [30]:
# Top states by customer count.
pd.read_sql_query('''
select state , count(customer_id) as total_customer_count from customers group by state order by total_customer_count desc''', engine)

           state  total_customer_count
0         Punjab                  1013
1    West Bengal                  1010
2      Rajasthan                  1000
3          Delhi                   998
4  Uttar Pradesh                   975
5      Karnataka                   971
6        Gujarat                   962
7    Maharashtra                   957
8     Tamil Nadu                   952
9        Haryana                   947

In [31]:
# Monthly customer acquisition.
pd.read_sql_query('''
select join_month as monthly_joined , count(customer_id) as customers_acquire from customers group by join_month order by join_month asc''', engine)

   monthly_joined  customers_acquire
0         2020-07                132
1         2020-08                124
2         2020-09                129
3         2020-10                145
4         2020-11                129
..            ...                ...
69        2026-04                146
70        2026-05                126
71        2026-06                128
72        2026-07                 16
73        2032-01                 19

[74 rows x 2 columns]

In [32]:
customers.to_sql('customers',mysql_engine,if_exists='replace',index=False)

9785

In [33]:
customers.to_csv("C:/Users/abhis/OneDrive/Documents/abhishek/Data_Analyst_Abhishek/data_analyst/python_data/practice/enterprise ecommerce project/data/customers.csv", index=False)